#+title: Personal ledger cookbook
#+author: Jean Dupin

* Formalise transactions and balances
** Transactions
Let's note $N$ the total number of accounts. In practice, the number of accounts
may depend on time $t$ but for simplicity, let's ignore that dependence and set
$N$ to  $$\underset{u \leq t}{\sup N(t)}$$

At a given time $t$, a transaction $j$ is defined as $(\Delta^j_{i,t})_{1 \leq i \leq N}$
where $\Delta^j_{i,t}$ is the i-th posting against account $i$ of the
transaction $j$ at time $t$.
The fundamental accounting equation requires that the transaction is balanced i.e.:
$$\forall j \sum_{i=1}^N\Delta^j_{i,t} = 0$$

At a given time $t$, there can be ($n$) multiple transactions. For simplicity, let's
roll all postings to the same account $i$ into a single posting at time $t$:
$$\Delta_{i,t} = \sum_{j=1}^n\Delta^j_{i,t}$$

Trivally, we have $\sum_{i=1}^{N}\Delta_{i,t} = 0$

** Trial balance
The trial balance of an account $i$ at time $t$ is defined as:
$$B_{i,t} = \sum_{u \leq t}\Delta_{i,u}$$

By construction, we have:

$\sum_{i=1}^N B_{i,t} = \sum_{i=1}^{N}\sum_{u \leq t}\Delta_{i,u} = \sum_{u \leq t}\sum_{i=1}^{N}\Delta_{i,u} = 0$

*At any time, the sum of balances across all accounts must be 0.*

** Clearing income
Let's note $IN$ the set of all income accounts. The income $I$ over a period t1, t2 is defined as
$$I_{\]t_1, t_2\]} = \sum_{i \in IN}\sum_{t_{1}\leq t \leq t_{2}}\Delta_{i,t}$$
Let's roll all postings to income accounts at time $t$ into a single posting $\Delta_{I,t}$
where $\Delta_{I,t} = \sum_{i \in IN}\Delta_{i, t}$

$\sum_{t_{1} \leq t \leq t_{2}}\Delta_{I,t} = \sum_{t \leq t_{2}}$

* The fundamental accounting equation
With signed quantities, the fundamental accounting equation is
$$A + L + E = 0$$.
This means that every new transaction must maintain this balance.
For example, an increase in assets must be offset by either:
- a decrease in another asset
- an increase in liabilities
- an adjustment in equity.

Examples:
- I buy a coffee for EUR 5 with my debit card. My assets decrease by EUR 5.
  This is an expense that decreases my overall net worth, hence an equity
  decrease (in absolute terms) of EUR 5.
- I buy a coffee for EUR 5 with my credit card. My assets do not change.
  However my liabilities increase by 5 EUR and they are matched by a
  decrease in equity.

* The fundamental rule of double-entry accounting
The fundamental rule of double-entry accounting requires every debit
to be matched with a credit of equal value.

Example of a violation of the rule:
#+begin_src ledger
2020-02-01 buy ada
    assets:cc:ada          2000 ADA
    assets:bank:checking   -$40
#+end_src ledger

The units ADA and USD are not directly convertible in the system so it
seems like value is appearing out of nothing/disappearing.
It is therefore imperative to indicate the implicit unit price or unitcost
#+begin_src ledger
2020-02-01 buy ada
    assets:cc:ada          2000 ADA @@ $40
    assets:bank:checking   -$40
#+end_src ledger

To fully enforce the rule of double-entry, it would be preferable to have
#+begin_src ledger
2020-02-01 buy ada
    assets:cc:ada          2000 ADA
    equity:conversion      -2000 ADA
    equity:conversion       $40
    assets:bank:checking   -$40
#+end_src ledge
But this general form is not recognised by hledger and reporting @ cost will not
be possible. Unless the transaction is booked with all postings and unitcost/unitprice.

#+begin_src ledger
2020-02-01 buy ada
    assets:cc:ada          2000 ADA @@ $40
    equity:conversion      -2000 ADA @@ $40
    equity:conversion       $40
    assets:bank:checking   -$40
#+end_src ledge

* Equity accounts
- Equity represents what's left for the owner after substracting liabilities
  from assets. It is the *net worth*.
- Equity is what funds the business, it is the business's obligation to the
  owner (a liability on the other hand is an obligation to a creditor). It
  represents an ownership's stake.
- Simple illustration: my financial life is the entity/business that is funded
  by the equity. So it "owes" money to the owner whose stake is materialised
  in the equity account.
- A positive equity means the owner owes the creditors of the entity.
- This is well illustrated with a shared asset because the value that is owned
  by the co-owner will be directly represented by the co-owner's equity.

* Shared assets and expenses in household ledger
** How do I represent a shared expense?
1. Record the full cash movement from the joint account to an expense account.
2. Reallocate each contributor's share to a specific equity account.
   No cash is moved - this is just an accounting trick to isolate the amount
   in a specific account.

#+begin_src ledger
2025-04-11 * Frais de courtier
    Assets:FR:CCF:Compte-Joint             EUR -3000
    Expenses:Finance:Mortgage               EUR 3000
    Equity:Jean:Assets:FR:CCF:Compte-Joint  EUR 1500
    Equity:Jean:Expenses:Finance:Mortgage  EUR -1500
    Equity:Aurelie:Assets:FR:CCF:Compte-Joint  EUR 1500
    Equity:Aurelie:Expenses:Finance:Mortgage  EUR -1500
#+end_src ledger

* How to log 111 company investment plan?
** Difficulties
111 cap pays annually into an investment plan as part of the
participation/interessement scheme.
The money is managed through EPSOR whereby it is invested in various mutual
funds.
Considering the allocation/rebalancing is automated, it would be cumbersome to
track the value of each fund.

** Solutions
Use a custom commodity to track contributions and value total.
#+begin_src ledger
commodity EURPER
commodity EURPEI

2024-11-19 * Versement defiscalise vers le PER
     Assets:FR:Epsor:PER:Tax-Deferred        EURPER 2158 @ EUR 1
     Assets:FR:BforBank:LivretA             EUR -2158

P 2025-01-01 EURPER EUR 1.1
#+end_src ledger
This is cumbersome because it requires to calculate a price inferred from
the valuation of the plan at time $t$ divided by the contributions.
Additionnally, contributions made at times $t_1$ and $t_{2}$ should not be
valued with the same price because they have grown with different returns.

For valuation purposes it is easier to use a balance assertion using the
provider's valuation at a specific date and track the unrealised-pnl into a
specific equity account.
#+begin_src ledger
2025-02-28 * EPSOR valuation
    Assets:FR:Epsor:PEI                  = EUR 54248
    Equity:Unrealised-PnL:EUR
#+end_src ledger

This requires a regular balance assertion entry.
For audit purposes, it is preferable to use a balance assertion based on an
official valuation statement from the investment provider.

** How to track the unrealised PnL?
Whenever a balance assertion is entered, it will automatically adjust the
corresponding equity account to match valuation changes.
It is then easy to track the PnL looking at the register of the equity account.
To facilitate granular tracking of a specific investment account, use a
corresponding equity account as below.

#+begin_src ledger
2024-12-31 * EPSOR PEI valuation
    Assets:FR:Epsor:PEI               = EUR 54886.46
    Equity:UnrealisedCapitalGains:Epsor:PEI
#+end_src ledger

>> hledger -f hledger.journal reg equity:unrealised.*epsor:pei  --width=150

** How to materialise the unrealised PnL?
The unrealised capital gains (or losses!) will accumulate in a chosen equity
account.
Capital gains are materialised by moving amounts from the equity account to
an income account.

#+begin_src ledger
2025-10-21 * Withdrawal
    Equity:UnrealisedCapitalGains:Epsor:PEI  EUR 8754.21
    Income:CapitalGains:Epsor:PEI  EUR -8754.21
#+end_src ledger

* How to deal with refunds?
** Refunds
As a general rule, should be logged as a transaction with a negative
expense posting. It is not an income, it actually should decrease
the accumulated balance held in the expense account.
#+begin_src ledger
2024-09-01 * AMEX - 2024-08-30 - Refund Bonne Gueule
    Assets:FR:BforBank:Compte-Courant         EUR 305
    Expenses:Shopping:Refunds                EUR -305
#+end_src

** Medical insurance refunds
- Best practice is to record the refund as a negative expense against the
  same account rather than as an income (it is not really an income).
- Alternative approach: track refunds separately in a dedicated account.
#+begin_src ledger
2024-02-20 * Insurance refund for doctor visit
    Assets:Bank:Checking              80 EUR
    Expenses:Health:Reimbursements   -80 EUR
#+end_src

* Country prefix
- For receivables and payables, what matters is the counterpary, not the
  country. A receivable is a receivable, regardless of whether your mother is in
  France or you repay a friend in London.
  *-> no need for a country prefix here* does not add semantic value.
* Useful queries
** Closing and retaining earnings
#+begin_src sh
hledger -f vincennes.journal close --retain --close-acct=Equity:Earnings:Retained
#+end_src

* Tracking property in Vincennes
** Design choices
- Use child accounts for each partner for assets, liabilities and expenses
  e.g. Liabilities:FR:CCF:Mortgage:Jean
- Use balanced virtual postings to track the property as a single asset
  regardless of ownership.
  This allows easy matching with bank statements for monthly transactions.
- The use of child accounts allows accurate reporting of what belongs to whom
  in joint-account. However, joint-account should be considered as a common pool
  of money and not something that is subdivided.
  The child division makes it easier to report on split of property-related
  expenses such as service charges, interest payments, etc.

** Compute total equity accumulated
#+begin_src sh
  hledger -f huchon.journal bal ^assets:property:jean ^liabilities.*jean
#+end_src

** Compute total mortgage repayment for principal
#+begin_src sh
  hledger -f huchon.journal bal liabilities.*jean not:desc:signature
#+end_src

** Compute running interest/service charges paid for each
#+begin_src sh
  hledger -f huchon.journal bal exp.*interest:jean
#+end_src

** Compute total capital contributed
#+begin_src sh
  hledger -f huchon.journal bal equity.*jean
#+end_src
